services:
    app.controller.api:
        class: AppBundle\Controller\APIController
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@translator']

#    recipe.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
