<?php

namespace AppBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUniqueNames(bool $published, string $locale)
    {
        $query = $this
            ->createQueryBuilder('i')
            ->select('i.name')
            ->join('AppBundle\Entity\Recipe', 'r')
            ->where('i.recipe_slug = r.slug')
            ->andWhere("r.language = '$locale'");
        if ($published) {
            $query->andWhere('r.published = 1');
        } else {
            $query->andWhere('r.published = 0')
                ->andWhere('r.finished = 1');
        }
        $query = $query->groupBy('i.name')
            ->getQuery();
        return $query->getResult();
    }
}
