<?php

namespace AppBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUniqueNames(bool $published)
    {
        $query = $this
            ->createQueryBuilder('i')
            ->select('i.name')
            ->join('AppBundle\Entity\Recipe', 'r')
            ->where('i.recipe = r.slug');
        if ($published) {
            $query->andWhere('r.isPublished = 1');
        } else {
            $query->andWhere('r.isPublished = 0')
                ->andWhere('r.isFinished = 1');
        }
        return $query->groupBy('i.name')
            ->getQuery()->getResult();
    }
}
