<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{

    public function find5mostViewed()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.title, r.slug
                FROM AppBundle:recipe AS r
                WHERE r.isPublished=1 AND r.isFinished=1
                ORDER BY r.views DESC'
            )
            ->setMaxResults(5)
            ->getResult();
    }

    public function find5bestRated()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.title, r.slug
                FROM AppBundle:recipe AS r
                WHERE r.isPublished=1 AND r.isFinished=1
                ORDER BY r.rating DESC'
            )
            ->setMaxResults(5)
            ->getResult();
    }

    public function getListPublished($categories)
    {
    	$query = $this->createQueryBuilder('r');
    	if ($categories != null) {
    		$query->add('where', $query->expr()->in('r.category', '?1'))
    		->setParameter('1', $categories);
    	}
    	return $query
    	->andWhere('r.isPublished = 1')
    	->getQuery()
    	->getResult();
    }
    
    public function getListForReview($categories)
    {
    	$query = $this->createQueryBuilder('r');
        if ($categories != null) {
	        $query->add('where', $query->expr()->in('r.category', '?1'))
	            ->setParameter('1', $categories);
        }
        return $query
            ->andWhere('r.isPublished = 0')
            ->andWhere('r.isFinished = 1')
            ->getQuery()
            ->getResult();
    }
}
