<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{

    public function find5mostViewed()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.title, r.slug
                FROM AppBundle:recipe AS r
                WHERE r.isPublished=1 AND r.isFinished=1
                ORDER BY r.views DESC'
            )
            ->setMaxResults(5)
            ->getResult();
    }

    public function find5bestRated()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.title, r.slug
                FROM AppBundle:recipe AS r
                WHERE r.isPublished=1 AND r.isFinished=1
                ORDER BY r.rating DESC'
            )
            ->setMaxResults(5)
            ->getResult();
    }

    public function getListPublished($categories, int $page, $sorter, string $direction = 'ASC')
    {
        if ($direction != "ASC" && $direction != "DESC") {
            throw new \InvalidArgumentException("Needs a correct direction to order");
        }
        return $this->getList($categories, $page)
            ->andWhere('r.isPublished = 1')
            ->orderBy('r.' . $sorter, $direction)
            ->getQuery()
            ->getResult();
    }

    public function getListForReview($categories, int $page, $sorter, string $direction = 'ASC')
    {
        return $this->getList($categories, $page)
            ->andWhere('r.isPublished = 0')
            ->andWhere('r.isFinished = 1')
            ->orderBy('r.' . $sorter, $direction)
            ->getQuery()
            ->getResult();
    }

    private function getList($categories, $page)
    {
        $query = $this->createQueryBuilder('r');
        if ($categories != null) {
            $query->add('where', $query->expr()->in('r.category', '?1'))
                ->setParameter('1', $categories);
        }
        return $query
            ->setFirstResult(($page - 1) * 10)
            ->setMaxResults(10);
    }

    public function getCount($published)
    {
        $query = $this
            ->createQueryBuilder('r')
            ->select('COUNT(r.title)');
        if ($published) {
            $query->where("r.isPublished = 1");
        } else {
            $query->where("r.isPublished = 0")
                ->andWhere("r.isFinished = 1");
        }
        return $query->getQuery()->getOneOrNullResult()[1];
    }
}
