language: php
php:
  - '7.0'
  - nightly

env:
    - SYMFONY_VERSION=origin/master

before_script:
  - cd ./Symfony
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit --coverage-text
