language: php
php:
  - '7.0'
  - nightly

env:
    - SYMFONY_VERSION=dev-master

before_install:
  - cd ./Symfony
  - cp app/config/parameters.yml.travis app/config/parameters_tests.yml
  - composer install

script:
  - phpunit --coverage-text
