language: php
php:
  - '7.0'
  - nightly

env:
    - SYMFONY_VERSION=dev-master

before_install:
  - cd ./Symfony
  - composer require symfony/http-foundation:${SYMFONY_VERSION}


script:
  - phpunit --coverage-text
