<?php

namespace RecipeBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function find5best() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.username, SUM(r.rating) AS ratings
                FROM RecipeBundle:User AS u
                JOIN RecipeBundle:recipe AS r WHERE r.author=u.id

                GROUP BY r.author
                ORDER BY ratings DESC'
            )
            ->setMaxResults(5)
            ->getResult();
    }
}
